apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lingshu.fullname" . }}-config
  labels:
    {{- include "lingshu.labels" . | nindent 4 }}
data:
  config.toml: |
    [server]
    addr = "0.0.0.0:8080"

    [log]
    level = "{{ .Values.env.LS_LOG_LEVEL }}"

    [database]
    url = "postgres://lingshu:lingshu_prod@{{ include "lingshu.fullname" . }}-postgresql:5432/lingshu"

    [redis]
    url = "redis://:redis_prod@{{ include "lingshu.fullname" . }}-redis-master:6379/0"
