apiVersion: v1
kind: ConfigMap
metadata:
  name: lingshu-config
  namespace: lingshu
  labels:
    app.kubernetes.io/name: lingshu
data:
  LS_ENV: "prod"
  LS_CLUSTER_ADDR: "0.0.0.0:9090"
  LS_LOG_LEVEL: "info"
  LS_FEDERATION_PORT: "9550"
  LS_FEDERATION_ENABLED: "true"
  LS_CLUSTER_NAME: "lingshu-cluster"
  LS_CLUSTER_SEED: "lingshu-federation"
  LS_PLUGIN_MARKET_ENABLED: "true"
  LS_PLUGIN_INSTALL_DIR: "/var/lib/lingshu/plugins"
  LS_PLUGIN_AUTO_DISCOVER: "true"
  LS_PLUGIN_REFRESH_INTERVAL: "300"
  LS_PLUGIN_SOURCES: "lingshu-org/lingshu-plugins"
