apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lingshu

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: lingshu
  app.kubernetes.io/managed-by: kustomize
