apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lingshu-data
  namespace: lingshu
  labels:
    app.kubernetes.io/name: lingshu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
